num_classes: 3
train_batch_size: 64

# Model
model: deeplab
backbone: resnet50
backbone_kwargs:
  dilated: True
  pretraining: resnet50_dilation.pth  # Filename of the pretraining weights (only backbone)
  padding_mode: zeros
model_kwargs:
  ndim: 32
  upsample: True
  upsample_embedding_mode: nearest
  use_classification_head: True
  classify_embedding: True
  pretraining: imagenet
  freeze_backbone: True

checkpoint: None

# MoCo
moco_kwargs:
   T: 0.5 # Temperature
   m: 0.999 # Momentum
   K: 128 # Negatives

# Optimizer:
epochs: 60
optimizer: sgd
optimizer_kwargs:
   lr: 0.005
   weight_decay: 0.0001
   momentum: 0.9
   nesterov: False
scheduler: poly

# Loss
loss_kwargs:
  reduction: mean

# Train:
train_kwargs:
  writing_per_epoch: 10
  saved_images_per_epoch: 8